apiVersion: v1
kind: Template
labels:
  app: mysqlexporter
  template: mysqlexporter-buildconfig
metadata:
  annotations:
    description: MySQL Exporter - BuildConfig
      see https://github.com/Worteks/docker-mysqlexporter
    iconClass: icon-openshift
    openshift.io/display-name: MySQL Exporter
    tags: mysqlexporter
  name: mysqlexporter-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds MySQL Exporter images
    labels:
      name: mysqlexporter-${FRONTNAME}-${MYSQL_EXPORTER_REPOSITORY_REF}
    name: mysqlexporter-${FRONTNAME}-${MYSQL_EXPORTER_REPOSITORY_REF}
  spec:
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${MYSQL_EXPORTER_REPOSITORY_URL}
        ref: "${MYSQL_EXPORTER_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: mysqlexporter-${FRONTNAME}:${MYSQL_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: MYSQL_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  value: master
- name: MYSQL_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your MySQL exporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-mysqlexporter.git
