apiVersion: v1
kind: Template
labels:
  app: mysqlexporter
  template: mysqlexporter-imagestream
metadata:
  annotations:
    description: MySQL Exporter - ImageStream
      see https://github.com/Worteks/docker-mysqlexporter
    iconClass: icon-openshift
    openshift.io/display-name: MySQL Exporter
    tags: mysqlexporter
  name: mysqlexporter-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in MySQL Exporter image
    name: mysqlexporter-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
